//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankEmployee
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public int BranchOffice { get; set; }
        public string GENDER { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
