//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int LoanID { get; set; }
        public string LoanType { get; set; }
        public decimal LoanAmt { get; set; }
        public int AccountNo { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
