//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int transID { get; set; }
        public System.DateTime TransTime { get; set; }
        public string TransType { get; set; }
        public int transFrom_accno { get; set; }
        public int transTo_accNo { get; set; }
        public decimal transAmount { get; set; }
        public string trans_remark { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
    }
}
