//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.orders = new HashSet<order>();
        }

        public int BookId { get; set; }
        public string BookName { get; set; }
        public int AuthorID { get; set; }
        public System.DateTime PublicationY { get; set; }
        public decimal Price { get; set; }
        public int StockAvail { get; set; }
        public int catagory { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Catagory Catagory1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
