//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int OrderID { get; set; }
        public System.DateTime OrderTime { get; set; }
        public int CustID { get; set; }
        public int Quantity { get; set; }
        public decimal BillAmount { get; set; }
        public int bookId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Book Book1 { get; set; }
    }
}
