//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attributes_In_MVC_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeJK
    {
        public int EmployeeId { get; set; }
        public string EmpName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Salary { get; set; }
        public string Designation { get; set; }
        public Nullable<int> DeptId { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
