//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DB_Demo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public Nullable<int> departmentid { get; set; }
    
        public virtual tblDepartment tblDepartment { get; set; }
    }
}
